### ISSUE TITLE
Signature is Invalid

### ISSUE THREAD

**Issue by b-risk** [Tsunami014/My-Grayjay-plugin#2]
Hi, just wanna let you know if you don't know already the plugin for YT Music will not work on other devices due to "the signature is invalid" error.

**Comment by Tsunami014** [comment]
I know, and it drives me crazy, I thought I did everything right

It's on my to fix list, don't worry

And I thought you could still install it even with an invalid signature by when you press install and it says it has an invalid signature you just press `install anyways`? Maybe not, I dunno.

**Comment by Tsunami014** [comment]
MB, aparently you cannot force install. Sorry for any confusion.

**Comment by Tsunami014** [comment]
Fixed!
